project:
  title: "ds105a-project-data-dabblers"
  type: website
  output-dir: docs 

format:
  html:
    css: styles.css
    toc: true

website:
  title: "Data Dabblers"
  navbar:
    background: primary
    search: true
    left:
      - href: index.html
        icon: ds105a-project-data-dabblers/images/menu.png
      - sidebar:eda
      - sidebar:visualisations
      - text: "Conclusions"
        href: conclusions.html
      - text: "Contributions"
        href: contributions.html

  sidebar:
    - id: eda
      title: "Exploratory Data Analysis"
      style: "docked"
      background: dark
      collapse-level: 2
      contents: 
        - text: "Data Collection"
          href: collection.html
        - text: "Data Cleaning"
          href: cleaning.html

    - id: visualisations
      title: "Visualisations"
      background: dark
      collapse-level: 2
      contents:
        - text: "Visualisations"
          href: visualisations.html